/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting.management;

import static java.lang.Integer.parseInt;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


public class Addvoter extends javax.swing.JFrame {

    /**
     * Creates new form AddVoter
     */
    public Addvoter() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    Connection con;
    PreparedStatement pst;
    private static final String CHAR_LOWER = "abcdefghijklmnopqrstuvwxyz";
    private static final String CHAR_UPPER = CHAR_LOWER.toUpperCase();
    private static final String NUMBER = "0123456789";
    private static final String DATA_FOR_RANDOM_STRING = CHAR_LOWER + CHAR_UPPER + NUMBER;
    private static SecureRandom random = new SecureRandom();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PasswrodLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jadd = new javax.swing.JButton();
        jclear = new javax.swing.JButton();
        AadhaarNumber = new javax.swing.JTextField();
        AadhaarNumberLabel = new javax.swing.JLabel();
        Gender = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Back_AddVoter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswrodLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PasswrodLabel.setText("Password");
        jPanel1.add(PasswrodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameLabel.setText("Full Name");
        jPanel1.add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Name.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(47, 46, 128), java.awt.Color.white));
        Name.setDisabledTextColor(new java.awt.Color(105, 105, 105));
        Name.setDragEnabled(true);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 180, 30));

        AddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddressLabel.setText("Address");
        jPanel1.add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        Address.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(47, 46, 128), java.awt.Color.white));
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 180, 30));

        GenderLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GenderLabel.setText("Gender");
        jPanel1.add(GenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        AgeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AgeLabel.setText("Age");
        jPanel1.add(AgeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 30, -1));

        Age.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(47, 46, 128), java.awt.Color.white));
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, 30));

        Password.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(47, 46, 128), java.awt.Color.white));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 180, 30));

        jPanel4.setBackground(new java.awt.Color(47, 46, 127));

        jadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Finish.png"))); // NOI18N
        jadd.setBorder(null);
        jadd.setContentAreaFilled(false);
        jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddActionPerformed(evt);
            }
        });

        jclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Refresh.png"))); // NOI18N
        jclear.setBorder(null);
        jclear.setContentAreaFilled(false);
        jclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jadd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jclear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jclear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jadd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 260, 40));

        AadhaarNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(47, 46, 128), java.awt.Color.white));
        AadhaarNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AadhaarNumberActionPerformed(evt);
            }
        });
        jPanel1.add(AadhaarNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 180, 30));

        AadhaarNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AadhaarNumberLabel.setText("Aadhaar Number");
        jPanel1.add(AadhaarNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, -1));
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, 30));
        Gender.add("");
        Gender.add("Male");
        Gender.add("Female");
        Gender.add("Others");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Format : xxxx xxxx xxxx");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 260, 500));

        jPanel2.setBackground(new java.awt.Color(47, 46, 128));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Add Voter");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Fingerprint.png"))); // NOI18N

        Back_AddVoter.setBackground(new java.awt.Color(47, 46, 127));
        Back_AddVoter.setForeground(new java.awt.Color(255, 255, 255));
        Back_AddVoter.setBorder(null);
        Back_AddVoter.setContentAreaFilled(false);
        Back_AddVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_AddVoterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Back_AddVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Back_AddVoter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(193, 193, 193))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddActionPerformed
        try {
            if(((Name.getText().length()==0) || (Age.getText().length()==0) || AadhaarNumber.getText().length()==0 || Address.getText().length() == 0 || Password.getText().length() ==0 || Gender.getSelectedItem()==Gender.getItem(0)) ){
                JOptionPane.showMessageDialog(null,"Empty field cannot be inserted");
            }
            else{
            String s=Age.getText();
        
            int user_age=Integer.parseInt(s);
            if(user_age<18){
                JOptionPane.showMessageDialog(null, "age must greater than or equal to 18");
            }
            
            else if((checkname(Name.getText())) && (checkage(Age.getText())) && checkAadhar(AadhaarNumber.getText()))
            {
                con = DriverManager.getConnection("jdbc:mysql://localhost/votingportal","root","");
                pst = con.prepareStatement("insert into addvoter1(password,name,address,sex,age,Aadhar_no,voterid)values(?,?,?,?,?,?,?)");
                pst.setString(1,Password.getText());
                pst.setString(2, Name.getText());
                pst.setString(3,Address.getText());
                pst.setString(4, Gender.getSelectedItem());
                pst.setString(5, Age.getText());
                pst.setString(6, AadhaarNumber.getText());
                String VoterID =generateVoterID(8);
                pst.setString(7,VoterID);
                pst.execute();
                String message_string = "Account created successfully\nVoterID :"+VoterID+"\nPassword :"+Password.getText()+"\nPlease save it";
                JOptionPane.showMessageDialog(null, message_string);
                Login l = new Login();
                l.setVisible(true);
                dispose();
            }
            else if(checkAadhar(AadhaarNumber.getText()) == false){
                JOptionPane.showMessageDialog(null, "Enter Aadhar number in proper format");
            }
            else if(checkname(Name.getText())==false){
                JOptionPane.showMessageDialog(null, "Enter alphabets only in Name");
            }
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Addvoter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jaddActionPerformed

    private void jclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclearActionPerformed

        Password.setText(null);
        Name.setText(null);
        Address.setText(null);
        Age.setText(null);
        AadhaarNumber.setText(null);
        Gender.select(0);
    }//GEN-LAST:event_jclearActionPerformed

    private void Back_AddVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_AddVoterActionPerformed
        Login ad = new Login();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_AddVoterActionPerformed

    private void AadhaarNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AadhaarNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AadhaarNumberActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addvoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addvoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addvoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addvoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addvoter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AadhaarNumber;
    private javax.swing.JLabel AadhaarNumberLabel;
    private javax.swing.JTextField Address;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField Age;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JButton Back_AddVoter;
    private java.awt.Choice Gender;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswrodLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jadd;
    private javax.swing.JButton jclear;
    // End of variables declaration//GEN-END:variables

    private String generateVoterID(int length) {
        StringBuilder sb = new StringBuilder(length);
        while(true){
            for(int i=0;i<length;i++){
                int rndCharAt = random.nextInt(DATA_FOR_RANDOM_STRING.length());
                char rndChar = DATA_FOR_RANDOM_STRING.charAt(rndCharAt);
                sb.append(rndChar);
            }
            if(checksafety(sb.toString())==1){
                break;
            }
        }
        return sb.toString();
        
    }

    private int checksafety(String ID) {
        try {
            final String queryCheck = "SELECT * from addvoter1 WHERE voterid = ?";
            final PreparedStatement ps = con.prepareStatement(queryCheck);
            ps.setString(1, ID);
            final ResultSet resultSet = ps.executeQuery();
            if(resultSet.next()){
                return 0;
            }
            else{
                return 1;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Addvoter.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 1;
    }
     /*int checkAadharnumber(String ID) {
        try {
            String queryCheck = "SELECT * from addvoter1 WHERE Aadhar_no = ?";
            PreparedStatement ps = con.prepareStatement(queryCheck);
            ps.setString(1,AadhaarNumber.getText());
            ResultSet resultSet = ps.executeQuery();
            if(resultSet.next()){
                return 0;
            }
            else{
                return 1;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Addvoter.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 1;
    }
    */
    private boolean checkname(String s) {
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            
            if(!(Character.isAlphabetic(c)) && (c!=' ')) {
                
                return false;
                
            }
        }
        return true;
    }

    private boolean checkage(String text) {
        /*String regex = "^[0-9]{3}$";
        Pattern pattern = Pattern.compile(regex);
        int user_age=Integer.parseInt(text);
        Matcher matcher = pattern.matcher(text);
        System.out.println(matcher.matches());
        return user_age>=18 && user_age<=200&& (matcher.matches());*/
        try{
        int user_age=Integer.parseInt(text);
        if(user_age>=18 && user_age<=200){
            
            return true;
        }
        else{
            return false;
        }
        
           }
        catch(Exception e){
            return false;
        }
        
    }

    private boolean checkAadhar(String text) {
        if(text.length()!=14){
            return false;
        }
        else{
        String regex= "^[2-9]{1}[0-9]{3}\\s[0-9]{4}\\s[0-9]{4}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(text);
        return matcher.matches();
        }
        
    }
}
        
        

