/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting.management;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.*;

import static java.awt.AWTEventMulticaster.add;
import java.awt.Color;


public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public AdminDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
Connection con;
PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        result = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Counting = new javax.swing.JButton();
        add_cand = new javax.swing.JLabel();
        display_voter = new javax.swing.JLabel();
        display_cand = new javax.swing.JLabel();
        delete_voter = new javax.swing.JLabel();
        delete_candidate = new javax.swing.JLabel();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jsjhdsajk");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jLabel5.setText("jLabel5");

        jRadioButton1.setText("jRadioButton1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(218, 223, 225));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/BVoterPortalTheme.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(47, 46, 127));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jButton1.setForeground(new java.awt.Color(218, 223, 225));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Logout.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        result.setBackground(new java.awt.Color(47, 46, 127));
        result.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        result.setForeground(new java.awt.Color(218, 223, 225));
        result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Result.jpg"))); // NOI18N
        result.setText("Result");
        result.setBorderPainted(false);
        result.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        result.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(47, 46, 127));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(218, 223, 225));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Profile.png"))); // NOI18N
        jButton3.setText("Profile");
        jButton3.setBorderPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Counting.setBackground(new java.awt.Color(47, 46, 127));
        Counting.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        Counting.setForeground(new java.awt.Color(218, 223, 225));
        Counting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Counting.png"))); // NOI18N
        Counting.setText("Counting");
        Counting.setBorderPainted(false);
        Counting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Counting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Counting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountingActionPerformed(evt);
            }
        });

        add_cand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_cand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_cand.setText("Add Candidate");
        add_cand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_cand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_candMouseClicked(evt);
            }
        });

        display_voter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        display_voter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        display_voter.setText("Display Voter List");
        display_voter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        display_voter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_voterMouseClicked(evt);
            }
        });

        display_cand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        display_cand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        display_cand.setText("Display Candidate List");
        display_cand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        display_cand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_candMouseClicked(evt);
            }
        });

        delete_voter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete_voter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete_voter.setText("Delete Voter");
        delete_voter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_voter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_voterMouseClicked(evt);
            }
        });

        delete_candidate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete_candidate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete_candidate.setText("Delete Candidate");
        delete_candidate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_candidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_candidateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(delete_voter, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(delete_candidate)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(display_voter, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(display_cand, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_cand, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Counting, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(add_cand, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(display_voter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Counting, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(display_cand)
                        .addGap(31, 31, 31)
                        .addComponent(delete_voter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(delete_candidate)))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        System.out.println("The admins details are as below :");
        System.out.println(Login.admin_name);
        System.out.println(Login.user_password);
        admin_profile profile = new admin_profile();
        profile.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_candMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_candMouseClicked
       add_cand.setForeground(Color.red);
       AddCandidate a=new AddCandidate();
       a.setVisible(true);
       dispose();
        
    }//GEN-LAST:event_add_candMouseClicked

    private void display_voterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_voterMouseClicked
        Dispalyvoterlist d=new Dispalyvoterlist();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_display_voterMouseClicked

    private void display_candMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_candMouseClicked
        display_cand.setForeground(Color.red);
        displaycandidatelist d=new  displaycandidatelist();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_display_candMouseClicked

    private void delete_voterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_voterMouseClicked
        delete_voter.setForeground(Color.red);
        Delete_voter dv = new Delete_voter();
        dv.setVisible(true);
        dispose();
    }//GEN-LAST:event_delete_voterMouseClicked

    private void delete_candidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_candidateMouseClicked
        delete_candidate.setForeground(Color.red);
        Delete_cand dc = new Delete_cand();
        dc.setVisible(true);
        dispose();
    }//GEN-LAST:event_delete_candidateMouseClicked

    private void CountingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountingActionPerformed
        Counting c=new Counting();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_CountingActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        votingresult v=new votingresult();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Counting;
    private javax.swing.JLabel add_cand;
    private javax.swing.JLabel delete_candidate;
    private javax.swing.JLabel delete_voter;
    private javax.swing.JLabel display_cand;
    private javax.swing.JLabel display_voter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton result;
    // End of variables declaration//GEN-END:variables
}
