/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting.management;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class VoterDashboard extends javax.swing.JFrame {

    /**
     * Creates new form VoterDashboard
     */
    public VoterDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Vote = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        Result = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Request = new javax.swing.JButton();
        Correction1 = new javax.swing.JButton();

        jButton2.setBackground(new java.awt.Color(47, 46, 127));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(218, 223, 225));
        jButton2.setText("Vote");
        jButton2.setBorderPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 46, 127));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/BVoterPortalTheme.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(218, 223, 225)));

        Vote.setBackground(new java.awt.Color(47, 46, 127));
        Vote.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Vote.setForeground(new java.awt.Color(218, 223, 225));
        Vote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Vote.png"))); // NOI18N
        Vote.setText("Vote");
        Vote.setBorderPainted(false);
        Vote.setFocusPainted(false);
        Vote.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Vote.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Vote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoteActionPerformed(evt);
            }
        });

        Profile.setBackground(new java.awt.Color(47, 46, 127));
        Profile.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Profile.setForeground(new java.awt.Color(218, 223, 225));
        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Profile.png"))); // NOI18N
        Profile.setText("Profile");
        Profile.setBorderPainted(false);
        Profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Profile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        Result.setBackground(new java.awt.Color(47, 46, 127));
        Result.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Result.setForeground(new java.awt.Color(218, 223, 225));
        Result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/ic_fingerprint_white_24dp.png"))); // NOI18N
        Result.setText("Results");
        Result.setBorderPainted(false);
        Result.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Result.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(47, 46, 127));
        Logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(218, 223, 225));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.setBorderPainted(false);
        Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logout.setInheritsPopupMenu(true);
        Logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Request.setBackground(new java.awt.Color(47, 46, 127));
        Request.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Request.setForeground(new java.awt.Color(218, 223, 225));
        Request.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Delete.png"))); // NOI18N
        Request.setText("Requests");
        Request.setBorderPainted(false);
        Request.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Request.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestActionPerformed(evt);
            }
        });

        Correction1.setBackground(new java.awt.Color(47, 46, 127));
        Correction1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Correction1.setForeground(new java.awt.Color(218, 223, 225));
        Correction1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/Update.png"))); // NOI18N
        Correction1.setText("UpdateID");
        Correction1.setBorderPainted(false);
        Correction1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Correction1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Correction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Correction1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Vote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correction1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Request, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Request, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(Vote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Correction1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        voter_profile vp = new voter_profile();
        vp.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProfileActionPerformed

    private void VoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoteActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/votingportal","root","");
            pst = con.prepareStatement("select*from addvoter1 where voterid=? and password=?");
            pst.setString(1, Login.voter_name);
            pst.setString(2, Login.voter_pass);
            ResultSet result = pst.executeQuery();
            while(result.next()){
            if(result.getBoolean("voting_status")==true){
                JOptionPane.showMessageDialog(this, "You already voted");
            }
            else{
               
                String sql="update addvoter1 set voting_status=1 where voterid='"+Login.voter_name+"'";
                PreparedStatement pst1 = con.prepareStatement(sql);
                pst1.executeUpdate(sql);
                Startelection select = new Startelection();
                select.setVisible(true);
                dispose();
            }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VoterDashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VoterDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VoteActionPerformed

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed

        votingresult_user uv = new votingresult_user();
        uv.setVisible(true);
        dispose();
    }//GEN-LAST:event_ResultActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Login adl = new Login();
        adl.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void RequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestActionPerformed
        Make_Request mr = new Make_Request();
        mr.setVisible(true);
        dispose();
    }//GEN-LAST:event_RequestActionPerformed

    private void Correction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Correction1ActionPerformed
        UpdateVoter uv = new UpdateVoter();
        uv.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_Correction1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoterDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Correction1;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Profile;
    private javax.swing.JButton Request;
    private javax.swing.JButton Result;
    private javax.swing.JButton Vote;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
